version: '3.8'

services:
  automated-database:
    image: postgres
    environment:
      POSTGRES_PASSWORD: root
      POSTGRES_USER: root
    ports:
      - "5432:5432"

  automated-spring-boot-app:
    build: .
    depends_on:
      - my-postgres
    ports:
      - "8080:8080"
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://my-postgres:5432/postgres

