version: '3.8'

services:
  automated-database:
    image: postgres
    environment:
      POSTGRES_PASSWORD: root
      POSTGRES_USER: root
    ports:
      - "5433:5432"

  automated-spring-boot-app:
    build: .
    depends_on:
      - automated-database
    ports:
      - "8090:8080"
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://automated-database:5432/postgres
