name: Docker and tests

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build-and-run:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Set up JDK 17 with cache
        uses: actions/setup-java@v4
        with:
          java-version: '17'
          distribution: 'temurin'

      - name: Maven build
        run: mvn -B package --file pom.xml

      - name: Build Docker images with Docker Compose
        run: docker-compose build

      - name: Start services with Docker Compose (detached mode)
        run: docker-compose up -d

      - name: Run unit tests (inside container)
        run: docker-compose exec my-app-service mvn jacoco:report mvn spotbugs:check mvn checkstyle:check  # Replace with your service name

      - name: Stop services with Docker Compose
        run: docker-compose down
